use_default_settings: true

server:
  port: 8080
  bind_address: "127.0.0.1"
  secret_key: "${SEARXNG_SECRET}"
  limiter: false
  public_instance: false
  image_proxy: false
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

search:
  formats:
    - html
    - json

valkey:
  url: valkey://valkey:6379/0
