
[[block]]
block = "cpu"
format = " $icon $utilization "
interval = 1

[[block]]
block = "memory"
format = " $icon $mem_used "

[[block]]
block = "net"
format = " $icon { $bitrate | 0b } "

[[block]]
block = "sound"
format = " $icon { $volume | 0% } "

[[block]]
block = "backlight"
format = " $icon $brightness "

[[block]]
block = "battery"
format = " $icon $percentage {$power} "
full_format = " $icon $percentage {$power | 0W} "
empty_format = " $icon $percentage {$power} "


[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %Y-%m-%d %R %Z') "
interval = 60

[icons]
icons = "icon.toml"

[theme]
theme = "theme.toml"
