openrouter_api_key: ENC[AES256_GCM,data:n7Zzz/o951D7vC+KKU/ZyG1863CaCueuxkq/mrzUJI7KkGt/cCPmrhbvCsU4O5M8UkyA4zVDmdga7I4aOY8yqCuvm2nKrhZdmw==,iv:OhNncxyxzRBveKHf6owoRz1WPmX1tpsiSOSXzrIO/xI=,tag:nMylxAu9PL5ecXz3ccSjeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvK0RCZWJZSUJsYjNnUW9I
            RGM2aHpUTWNNNFpZeTQyTnNQZFlGRVRzSEFvClB4Y1VKSDd2aGxFejdyZUlmcDV2
            TUI2OGM4cUorYnN6WWovS1dPL2pVNjQKLS0tIDNTUXRXMm9zNUZ6encvUjd5UDNh
            VElseDBUN1RGSHRDVnlHdjZpbGhEelEK4mOEg5GJSD2Hs3Wo4W6yIN5xk+qBWLer
            HSBssYPU6IKB/hD/tfKyxv4Ir3d9zHVmZeS6bBz6LEtAwRHoeMaq8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnrrtyd5f86495mky7ghaz85whpnlqa9jrhk45vskcyj3v5dh4tqavsruf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOTRUbjU0NCs0TnRReldm
            dWJMNXFlc0p4cFdJbjh4aXlxYy8rc24yd3cwCk9SNjhvYjZtT3g3Z05YcmtTM2VO
            TzZsRyt3T0pXNmJRd0tsMXZVS1VHZ1kKLS0tIGNEOGFDbjFOMHkxOGRPelI4MDVs
            RXlRL0N5RmcyaEdmWWI3WjZGR0R2aVUKgX+6K8iegQkXpIB//62AWdzsGJli0BTF
            CNdA/7ATUwtzpfizXVJ0Dwn6YlNUar/LbWFci5VF0olMz//3A0qHyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13e89sh8en5ulvgq4afkj6hrsvk3l0jqnpteh7ykatv7k6cp30ayq9jhv7k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTjUwbGZEbGUxNHdpK1hS
            Yjd3ckRFQmQwSmgybzJBbVpGR0pZeTRjUm5JCjd1OGxYSlU2bGdQWHBYSVBJemZp
            bklITWNYbkxFTWs5MGxwQ1JVMGttWU0KLS0tIDYvOUMvbnRQVU5Rc0pLRWZ2MThi
            Y1UxczMza0hNMENOL1RTQmVXL2pGZHcKwjLgQ7eGKjHzcZmGDXbsJ9SvkSSTTFSx
            X3x9EoFipxtxtPmUW1G9uHNzQEA1cS8XUJAhPhXw4fqYZ/8Dk1WkBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xfmc05rat3wxuhlqwxnw9zv08nz25gxvy32jwlp68y9xjwft342swudumh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YnQ4WVhKd0wzNkFKOTUv
            K2szWnZ4bjdBR3RTMlRGdFVJdVhES1pydFF3Cmo2QmJPc0t6M0VVWXZJNExOUkIy
            bHZsalNYRDhQRHpqd2ZuWE0zOVQvSGcKLS0tIE9kbHI5QzRrbzdoaFg2clNvakYv
            N3NtcTc4cVROdnlYWlAzMW40VmJ1cDAKqjCyNi5Xv26PJ4Iqv/mjVooMeEDUCNy7
            czQZQLbCAvFsXUzROPGSiErFTsN4OVSStFbf96hJF9Q1KlTLYRlkFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18vvn73x485gy2uel247u0shnekl570e4t5acelpzm9qvukv9kvqszefrza
    lastmodified: "2026-06-21T21:31:50Z"
    mac: ENC[AES256_GCM,data:iGl5DT5Xyv+G5IRVN78mzoaIi0099vbxWcPkPdN1XnXq7VvUeWMmewfwf2rJjkCNrIReq4VKjVNy4j3w5OdIs9fyZ2OkLRl85CNmSOV9YMW9NQshnokmplX9MEfLzZvDG2xVhoHSCr2oUTs+rTyZWO9sFsD6gQqyuRZBmpb8FOw=,iv:BWQkxaGEBWc6IgXacGgikRkjpdY8cFnzrt5cbAH2DTo=,tag:6i5W/q7+BrBFoA2o4N9r5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
