NAMECHEAP_API_USER: ENC[AES256_GCM,data:Nj+rvvhZrtJ/XAZv,iv:Cyfvo9jH7n3y7XJTs71SEDA+7HGzeA7VGm9AEJHt8UU=,tag:yFpNk41kx+MKkdPPlL/wWQ==,type:str]
NAMECHEAP_API_KEY: ENC[AES256_GCM,data:XJ/uHqBFJxkZJ2qRm/7uCC1fHYwnyBypNAV2mLWVJqA=,iv:szIvuewj77/DTARR88OZHdfyp9XerCBWQS4woudH6sQ=,tag:aK9Wa+YWrPjUIAjqfRJeaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpR1h4Y1B3ZFExK1BFaHZP
            UEF5MzYvT1dSaWgva1cvT2NQUFFWK0ZJWDJJClVVUHgvRFRMRFZ2R2JlTFJMUTJx
            R0I5UWNLWlNjOWg4cDVlOHdYNExRNW8KLS0tIHNFNUEwT2tYMXVVd09ycmlZcllX
            bzl2dUQ3OTVYM1MzeXFGTzM4RzVaZE0KgPBd/dBDfnSjh2CFKAf/NJC19egtlQwY
            SpwKI+j5t2eTgcatyTTCQyXY5t9xjtCkRvw2vGqfWgeSVn7BxTd4/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vnrrtyd5f86495mky7ghaz85whpnlqa9jrhk45vskcyj3v5dh4tqavsruf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeDQ0YmdveUpHU2ZYKzUr
            Yk1Mb0FjeVBveTNDTU5xM2VTUHRWVnlTTTIwCllOc3NpWWZCeHdVUmNaY2V0Ylk0
            M0Urb0ljTmFwRTN0SmI3WUIrbGtqRW8KLS0tIFNXdTB6U0U1T0pEbWJRMjlXMHo3
            M2p2L0Z4NFVsa2NPS01ac1FWN2t0VTAKKid6SHpXDSdYcC5TqvKKQdRIzTBrK4JZ
            nedP8T4tPadi+MtJBDd7jK2pZil+w22ePCX4Sy9uDKbZ90/5mnM/hQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13e89sh8en5ulvgq4afkj6hrsvk3l0jqnpteh7ykatv7k6cp30ayq9jhv7k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WTdobjBZazJOWjFtZ2FD
            ZjVPK2ZtZ2x2Qm5hd056b1R5SGJXQjYrN1ZNCml3NDJmdEhGVzlGekswZXlYQngw
            VS9RUGtQZjZHVnpQWk9tUVZ4cEdaTTAKLS0tIEhtZkVoMTNsNjBJeHBYUWNoVVRt
            TXcrcDRqT1BvaUlaMXhOaHFFK3Y2TTgKSSEklscwHFPFFTOb+hx3cnrLxz9Z31J9
            FGrQsaSDFLjFE2qOWgIOIwHzB26sCKkO80YMEbj11USj1QdCyaRzkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xfmc05rat3wxuhlqwxnw9zv08nz25gxvy32jwlp68y9xjwft342swudumh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWTVzSFJ2eE56cUxFenRD
            emJaTFc4RVBFQzg5Nzdlb1BiZHNKcHd3cTBRCi8xbEEzR1VJQXRjRnlkN0M3c1Vz
            S3J5RTZ0QzZkR2VJYXg5cjdySnR1TFkKLS0tIEFMR29BOGpzZzBIc0VIZWNaRk1r
            dStralZHVVhRVFlpNHJHdHpwbmoyR3cK7mYHveWKMa3qen1NObFJJjhiBNs1LwDU
            mVZNCimoEcgCHtEc+IntEwL6E+5Gnq6md/leuAdQXzYaB/CY1ra4yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18vvn73x485gy2uel247u0shnekl570e4t5acelpzm9qvukv9kvqszefrza
    lastmodified: "2026-05-23T00:38:02Z"
    mac: ENC[AES256_GCM,data:KXwkMNmgDaPMg3kiAMBSCwYPjeSpmimXYY8OOJofuwpZMjuuSZJU8kRJL8rrEGCJwr/6EueftOdAxiwbK0k3NUCFsPBGnA3Jl00vu+ImwtBmGSkodKDXkPbfMgrWDuPOgoYMQdoBm7mpT+YIZ0ABOvmSUgfOG1XzvSN0txjrBmg=,iv:9PUlkSPz1/9MY1gCLk9TB7tZL9Syjx9sZr8NzjCru5o=,tag:CuiD1qq7VPA1cBBeamGZMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
