# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
#
zstyle ':completion:*:*:*:default' menu yes select search # Enhanced tab completion

eval "$(zoxide init zsh --cmd j)"

HISTFILE=~/.histfile 
HISTSIZE=5000 
SAVEHIST=5000

setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits. 
setopt SHARE_HISTORY             # Share history between all sessions. 
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again. 
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate. 
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found. 
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space. 
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file. 
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry. 
setopt interactivecomments       # Allow typing comments at an interactive prompt 
setopt correct                   # Suggest spelling suggestions for mistyped commands

# Aliases
# alias ls='ls --color=auto'
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias cp="cp -i"
alias df="df -h"
alias ls="lsd"
alias ssh="TERM=xterm-256color ssh"
alias cat="bat"

alias vim=nvim

alias ranger='ranger --choosedir=$HOME/.rangerdir' # Write last visited directory
alias visit='cd `cat $HOME/.rangerdir`' # Visit ranger directory

alias icat="kitty +kitten icat" # image cat

alias find="fd"

alias notemk="touch `date -I`.txt"
alias enote='nvim `ls -1 | grep -P \"\d{4}-[01]\d-[0-3]\d\.txt\" | tail -1`'

autoload -z edit-command-line
zle -N edit-command-line
bindkey -v
bindkey "^X^E" edit-command-line

bindkey "^[[3~" delete-char # Make 'delete' actually delete 
bindkey \^U backward-kill-line  # Ctrl-U works as in bash 
bindkey "^[[1;5C" forward-word  # Ctrl-right moves right a word 
bindkey "^[[1;5D" backward-word # Ctrl-left moves left a word

export EDITOR='nvim'
export VISUAL='nvim'

export DEBUGINFOD_URLS='https://debuginfod.elfutils.org/'
export DEBUGINFOD_PROGRESS=1

autoload -Uz compinit
compinit
# Completion for kitty
kitty + complete setup zsh | source /dev/stdin

# . /usr/share/powerline/bindings/zsh/powerline.zsh
if [ -n "${commands[fzf-share]}" ]; then
    source "$(fzf-share)/key-bindings.zsh"
    source "$(fzf-share)/completion.zsh"
fi


ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

zinit ice depth=1; zinit light romkatv/powerlevel10k

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

zinit light "Aloxaf/fzf-tab"
zinit light "MikeDacre/tmux-zsh-vim-titles"
# zinit light "MichaelAquilina/zsh-autoswitch-virtualenv"
zinit light "zdharma-continuum/fast-syntax-highlighting"
zinit light "zsh-users/zsh-autosuggestions"
# zinit light "hcgraf/zsh-sudo"
zinit light "hlissner/zsh-autopair"
zinit light "jandamm/instant-repl.zsh"
zinit light "peterhurford/up.zsh"
zinit light "wfxr/forgit"


# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# preview directory's content with exa when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls'

export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket

export PATH=~/.local/bin:$PATH
