# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  sops.secrets."invidious/hmac_key" = {};
  sops.secrets."invidious/companion_key" = {};

  # Containers
  virtualisation.oci-containers.containers."invidious-companion" = {
    image = "quay.io/invidious/invidious-companion:latest";
    environment = {
      "SERVER_SECRET_KEY" = config.sops.placeholder."invidious/hmac_key";
    };
    volumes = [
      "invidious_companioncache:/var/tmp/youtubei.js:rw"
    ];
    extraOptions = [
      "--cap-drop=ALL"
      "--log-opt=max-file=4"
      "--log-opt=max-size=1G"
      "--network-alias=companion"
      "--network=invidious_default"
      "--security-opt=no-new-privileges:true"
    ];
  };
  systemd.services."podman-invidious-companion" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-invidious_default.service"
      "podman-volume-invidious_companioncache.service"
    ];
    requires = [
      "podman-network-invidious_default.service"
      "podman-volume-invidious_companioncache.service"
    ];
    partOf = [
      "podman-compose-invidious-root.target"
    ];
    wantedBy = [
      "podman-compose-invidious-root.target"
    ];
  };
  virtualisation.oci-containers.containers."invidious-invidious" = {
    image = "quay.io/invidious/invidious:latest";
    environment = {
      "INVIDIOUS_CONFIG" = "db:
    dbname: invidious
    user: kemal
    password: kemal
    host: invidious-db
    port: 5432
  check_tables: true
  invidious_companion:
  # URL used for the internal communication between invidious and invidious companion
  # There is no need to change that except if Invidious companion does not run on the same docker compose file.
  - private_url: \"http://companion:8282/companion\"
  # IT is NOT recommended to use the same key as HMAC KEY. Generate a new key!
  # Use the key generated in the 2nd step
  invidious_companion_key: \"${config.sops.placeholder."invidious/companion_key"}\"
  # external_port:
  # domain:
  # https_only: false
  # statistics_enabled: false
  # Use the key generated in the 2nd step
  hmac_key: \"${config.sops.placeholder."invidious/hmac_key"}\"
  ";
    };
    ports = [
      "127.0.0.1:3000:3000/tcp"
    ];
    dependsOn = [
      "invidious-invidious-db"
    ];
    extraOptions = [
      "--health-cmd=wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/stats || exit 1"
      "--health-interval=30s"
      "--health-retries=2"
      "--health-timeout=5s"
      "--log-opt=max-file=4"
      "--log-opt=max-size=1G"
      "--network-alias=invidious"
      "--network=invidious_default"
    ];
  };
  systemd.services."podman-invidious-invidious" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-invidious_default.service"
    ];
    requires = [
      "podman-network-invidious_default.service"
    ];
    partOf = [
      "podman-compose-invidious-root.target"
    ];
    wantedBy = [
      "podman-compose-invidious-root.target"
    ];
  };
  virtualisation.oci-containers.containers."invidious-invidious-db" = {
    image = "docker.io/library/postgres:14";
    environment = {
      "POSTGRES_DB" = "invidious";
      "POSTGRES_PASSWORD" = "kemal";
      "POSTGRES_USER" = "kemal";
    };
    volumes = [
      "/home/agentelement/dotfiles/configs/invidious/config/sql:/config/sql:rw"
      "/home/agentelement/dotfiles/configs/invidious/docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh:rw"
      "invidious_postgresdata:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
      "--network-alias=invidious-db"
      "--network=invidious_default"
    ];
  };
  systemd.services."podman-invidious-invidious-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-invidious_default.service"
      "podman-volume-invidious_postgresdata.service"
    ];
    requires = [
      "podman-network-invidious_default.service"
      "podman-volume-invidious_postgresdata.service"
    ];
    partOf = [
      "podman-compose-invidious-root.target"
    ];
    wantedBy = [
      "podman-compose-invidious-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-invidious_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f invidious_default";
    };
    script = ''
      podman network inspect invidious_default || podman network create invidious_default
    '';
    partOf = [ "podman-compose-invidious-root.target" ];
    wantedBy = [ "podman-compose-invidious-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-invidious_companioncache" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect invidious_companioncache || podman volume create invidious_companioncache
    '';
    partOf = [ "podman-compose-invidious-root.target" ];
    wantedBy = [ "podman-compose-invidious-root.target" ];
  };
  systemd.services."podman-volume-invidious_postgresdata" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect invidious_postgresdata || podman volume create invidious_postgresdata
    '';
    partOf = [ "podman-compose-invidious-root.target" ];
    wantedBy = [ "podman-compose-invidious-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-invidious-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
