idle_bg = "#1b1c1e"
idle_fg = "#a7aab0"
info_bg = "#1b1c1e"
info_fg = "#57a5e5"
good_bg = "#1b1c1e"
good_fg = "#8fb573"
warning_bg = "#1b1c1e"
warning_fg = "#dbb671"
critical_bg = "#1b1c1e"
critical_fg = "#de5d68"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
