bar:
  height: 32
  spacing: 12
  margin: 24
  location: top
  background: 1b1c1eff
  foreground: a7aab0ff
  font: "inconsolata:size=26"

  right:
    - backlight:
        foreground: 51a8b8ff
        name: "amdgpu_bl0"
        content:
          - string: { text: "light: {percent}" }

    - battery:
        name: "BAT1"
        foreground: 8fb573ff
        content:
          - string: { text: "bat: {capacity} drain: {estimate}" }

    - clock:
        time-format: "%H:%M:%S"
        date-format: "%Y-%m-%d"
        content:
          - string: { text: "{date} {time}" }


  center:
    - i3:
        content:
          "": {string: {text: ""}}
          current: { string: { text: "{application}" } }

  left:
    - i3:
       content:
         "":
           map:
             default: { string: { text: "{name}", right-margin: 24 }}
             conditions:
               state == focused: { string: { text: "{name}", right-margin: 24, foreground: 57a5e5ff }}

